// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfxyleqvulhilgawzeca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmeHlsZXF2dWxoaWxnYXd6ZWNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNzU0OTQsImV4cCI6MjA2ODg1MTQ5NH0.YaMKccF2jnNkItcan8D0CJrfW_OscB2xZ-7fr3nCGN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});